### ISSUE TITLE
Camunda API REST calls respond with 401 Unauthorized

### ISSUE THREAD

**Issue by gitdode** [camunda/camunda-sso-snippets#11]
Hello,

I've set up camunda-sso-jboss-keycloak, login with Keycloak to for example the Welcome page works fine and apps like Cockpit are listed.

Calling a REST service like api/engine/engine/default/process-definition from within the same browser session also works.

If I however send a valid access token with the "Authorization Bearer <access_token>" header, I get a "401 Unauthorized" response and when debugging, execution doesn't enter KeycloakAuthenticationProvider#extractAuthenticatedUser.

What could I be missing? I've attached web.xml:
[web.xml.txt](https://github.com/camunda/camunda-sso-snippets/files/4911934/web.xml.txt)

Cheers,
Torsten

**Comment by falko** [comment]
@nevries any idea on this?

**Comment by gitdode** [comment]
Please don't bother, it works just fine - I had a silly mistake in my test setup and it took me long enough to figure it out.

Sorry for the false alarm!

**Comment by falko** [comment]
Hi Torsten,

great to hear that you could solve your problem.

Cheers,
Falko
